services:
  - type: web
    name: n8n-service
    plan: free
    runtime: image              # 重點：用官方映像，不是 build Dockerfile
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

databases:
  - name: n8n-db
    plan: free
