services:
  - type: web
    name: n8n-service
    plan: free
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      # 如果你想用自己的網址作為 webhook 基礎 URL，可取消註解並替換：
      # - key: WEBHOOK_URL
      #   value: https://your-n8n-domain.onrender.com/
      # 開啟基本認證 (建議啟用，替換下面帳號密碼)
      # - key: N8N_BASIC_AUTH_ACTIVE
      #   value: "true"
      # - key: N8N_BASIC_AUTH_USER
      #   value: yourUsername
      # - key: N8N_BASIC_AUTH_PASSWORD
      #   value: yourPassword

databases:
  - name: n8n-db
    plan: free
    # diskSizeGB: 5  # 如需更大空間，取消註解並調整數值
